language: node_js
node_js:
  - "10.14.2"
cache: npm
jobs:
  include:
    - stage: tests
      name: "lint:all"
      script: npm run lint:all

    - stage: tests
      name: "test:contracts"
      script: npm run test:contracts

    - stage: tests
      name: "test:utils"
      script: npm run test:utils

    - stage: tests
      name: "Solidity Coverage"
      script:
        - npm install codecov
        - npm install https://github.com/leapdao/solidity-coverage.git#master
        - npm run coverage
        - ./node_modules/.bin/codecov -f coverage/lcov.info

    - stage: tests
      name: "test:contracts with geth"
      before_script:
        - wget 'https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.22-7fa3509e.tar.gz' -O - | tar -xz; mv geth-*/geth .
      script: PATH=`pwd`:$PATH ./scripts/test_geth.sh test/contracts/*
