language: node_js
node_js:
  - "lts/*"
cache:
  - yarn
  - npm
jobs:
  include:
    - stage: tests
      name: "lint:all"
      script: yarn lint:all

    - stage: tests
      name: "test:contracts"
      script: yarn test:contracts

    - stage: tests
      name: "test:utils"
      script: yarn test:utils

    - stage: tests
      name: "Solidity Coverage"
      script:
        - yarn add codecov
        - yarn add https://github.com/leapdao/solidity-coverage.git#7b3ae478f2777dc72c813fe16e937e09670e3587
        - yarn coverage
        - ./node_modules/.bin/codecov -f coverage/lcov.info

    - stage: tests
      name: "test:contracts with geth"
      before_script:
        - wget 'https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.22-7fa3509e.tar.gz' -O - | tar -xz; mv geth-*/geth .
      script: PATH=`pwd`:$PATH ./scripts/test_geth.sh test/contracts/*

    - stage: tests
      name: "test ExecutionPoker cli tool"
      script:
        - yarn compile:contracts
        - ./tools/executionPoker/bin.js build/contracts/SpendingConditionMock.json test 0xD8992E08C1Fb17775deF02e15B620A006c4726db [] []
